# Generated by Django 3.2.18 on 2023-03-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SerwisOgloszenApp', '0003_adimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
    ]
