# Generated by Django 3.2.18 on 2023-04-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerwisOgloszenApp', '0004_remove_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='Podkarpackie', max_length=20),
            preserve_default=False,
        ),
    ]
