# Generated by Django 3.2.18 on 2023-06-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SerwisOgloszenApp', '0006_ad_reserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='reserver',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to='SerwisOgloszenApp.customer'),
        ),
    ]
